# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c0358f1c71396cb13b983a4f89db48aa2066e665fcb7b0f71e2f8189a15da0e5406df2bb658e0eacfe30e77e10fc67df24fb9614d4413564653fee2ddca36b18

test:
  secret_key_base: 47ce6c6f39cfc46360ddec579bcd2e2f46fa23868a2f0beb39446028b7d7fd163f6c217ab4f2dffeab28e15390c29aa13fdf0f28134024b167c36ceef29fa4cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
